name: Deploy Frontend

on:
  push:
    branches:
      - main # 适配你的主分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.17.0'

    - name: Install Dependencies
      run: npm install

    - name: Build Frontend
      run: npm run docs:build

    - name: SSH and Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        script: |
          # 创建远程目录
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} -p ${{ secrets.SERVER_SSH_PORT }} 'mkdir -p /www/web'
          
          # 传输构建好的前端资源到远程服务器
          scp -r -P ${{ secrets.SERVER_SSH_PORT }} dist/* ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/www/web
